data_param:
  batch_size: 2 # batch size, most ideal is 64
  data_root: /home/dungmaster/Datasets/Fashion-Outfits-Theme-Aware # data root
  image_root: /home/dungmaster/Datasets/Fashion-Outfits-Theme-Aware  # image root
  data_set: train # data set
  outfit_desc: outfit_description # description embedding of outfits
  nega_mode: RandomOnline # negative outfits strategy
  num_workers: 2 # number of workers
  use_lmdb: true # use lmbd data
  use_semantic: false # use sentance data
  use_visual: true # use visual data
  transforms: False  # whether to augment image
  num_pairwise: [2, 3, 4]
  using_max_num_pairwise: true

train_data_param:
  shuffle: true # do shuffle
  data_mode: PairWise # output data format
  phase: train # split

test_data_param:
  shuffle: false # do not shuffle
  data_mode: PairWise # output data format
  phase: val # split

net_param:
  name: FashionNet
  num_users: 1 # number of users ##TODO: Later
  dim: 128 # dimension of binary codes
  outfit_semantic_dim: 512 # dimension of outfit embedding vector
  # backbone: alexnet # backbone for feature extractor
  hash_types: 3 # type of hash codes, current only use for item
  scale_tanh: true # use scale tanh
  use_semantic: false # use semantic features
  use_visual: true # user visdual features
  margin: 0.1 # margin for vse-loss, if exists
  shared_weight_network: true
  pairwise_weight: 1.0
  outfit_semantic_weight: 1.5

gpus: [0]

# load_trained: /home/dungmaster/Projects/Machine Learning/HangerAI_outfits_recommendation_system/Hash4AllFashion/checkpoints/fhn_t3_osem_best_11_26.pt
# load_trained: /home/dungmaster/Projects/Machine Learning/HangerAI_outfits_recommendation_system/Hash4AllFashion/checkpoints/11_28_23/fhn_t3_osem_pretrained_best_11_28.pt
# load_trained: /home/dungmaster/Projects/Machine Learning/HangerAI_outfits_recommendation_system/Hash4AllFashion/checkpoints/fhn_t3_osem_pretrained_allCate_best_11_28.pt
load_trained: /home/dungmaster/Projects/Machine Learning/HangerAI_outfits_recommendation_system/Hash4AllFashion/checkpoints/11_29_23/fhn_osem_allCate_11_29_best.pt

## Deploy options
# score_type_selection: "binary"
score_type_selection: "latent"
feature_type_selection: "visual"
num_recommends_per_choice: 5
num_recommends_for_composition: 3
get_composed_recommendation: True