data_param:
  batch_size: 2 # batch size, most ideal is 64
  data_root: /home/dungmaster/Datasets/polyvore_outfits # data root
  image_root: /home/dungmaster/Datasets/polyvore_outfits  # image root
  data_set: disjoint # data set
  nega_mode: ShuffleDatabase # negative outfits strategy
  num_workers: 2 # number of workers
  use_lmdb: true # use lmbd data
  use_semantic: true # use sentance data
  use_visual: false # use visual data
  cate_selection: ["top", "bottom", "bag", "outerwear", "shoe"]
  num_pairwise: [2, 3, 4]
  using_max_num_pairwise: true

train_data_param:
  shuffle: true # do shuffle
  data_mode: PairWise # output data format
  phase: train # split

test_data_param:
  shuffle: false # do not shuffle
  data_mode: PairWise # output data format
  phase: val # split

net_param:
  name: FashionNet
  num_users: 1 # number of users ##TODO: Later
  dim: 128 # dimension of binary codes
  backbone: alexnet # backbone for feature extractor
  hash_types: 2 # type of hash codes, current only use for item
  scale_tanh: true # use scale tahn
  use_semantic: true # use semantic features
  use_visual: false # user visdual features
  margin: 0.1 # margin for vse-loss, if exists
  shared_weight_network: true

solver_param:
  name: "FashionNetSolver"
  display: 100 # display interval
  test_display: 100  # display test interval
  epochs: 100 # total epoches
  gamma: 1.0 # gamma for scale-tanh
  gpus: [0]
  ##TODO: using tensorboard
  tracking_method: "tensorboard"
  tracking_log_dir: "./logs/fashion_hash_net_t3_allFashion_noVisual"
  ##TODO: Delete this visdom option
  visdom_env: fashion_hash_net
  visdom_title: fashion_hash_net_t3_allFashion_noVisual
  checkpoints: ./checkpoints/fashion_hash_net_t3_allFashion_noVisual
  optim_param:
    name: SGD
    # lr: [5, 0.001, 0.005, 0.005, 0.01] # learning rate for each group
    # lr: [10, 0.001, 0.01, 0.01, 0.1] # features, user_encoder, encoder_v, encoder_t, matching_weight
    # lr: [10, 0.01, 0.1]
    # lr: [0.01, 0.001, 0.001, 0.01] # features, encoder_v, classifier_v, core
    lr:
      features: 0.01
      encoder_t: 0.001
      classifier_t: 0.001
      core: 0.01
    weight_decay:
      features: 1.0e-05
      encoder_t: 1.0e-05
      classifier_t: 1.0e-05
      core: 1.0e-05
    grad_param: { momentum: 0.9 } # setting for SGD
    lr_scheduler: ReduceLROnPlateau
    scheduler_param:
      { cooldown: 10, factor: 0.5, patience: 10, threshold: 0.05 }

log_file: logs/train/fashion_hash_net_t3_allFashion_noVisual.log
log_level: DEBUG